### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by NewAlexandria** [wponrails/wponrails.org-rails#1]
We have been building rails models for interfacing with the WP database structure.  I thought I would see if there are any synergies here.  

It looks like rails models are not used to get the data; but rather an WP endpoint?

**Comment by sebastiaandegeus** [comment]
This project is alive. We use it in production for a dozen news websites.

The models on the Rails side are merely cached copies. The real data lives in the WordPress database. When data gets updated in WP it sends a webhook nudge to Rails to tell it to fetch the data from the WordPress API and update all relating models like attachments, tags, taxonomies.

**Comment by NewAlexandria** [comment]
What advantages made you choose to pull and cache WP data, over reading directly from the DB with WP tables? I understand that the WP database is very unlikely active record and has other undesirable conventions.

**Comment by cies** [comment]
We believe the WP DB structure is not a stable touchpoint; in contrast to the (soon to be incorporated in in wp-core) REST API. We cache the data as it gives us a performance advantage, it's nice to have the data in a clean-cut database model: easy to reason about, easy to optimise and easy to extend upon.

That last point "easy to extend upon" is quite big actually. In the Rails app the data from WP may coexist (and associate) with data from other sources. For instance "end user login" is a typical feature we would implement solely in the Rails app. In that case WP does not know anything about "end users", it merely serves as a admin backend for web content editors.
